# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c007da0e508e55c9027511266685f56793a9932685bf23cb86160fe38b9617fead71b9bc18a5d14a622b5059b43f93b83a98747653dc1878fc16b93fdb60ec98

test:
  secret_key_base: 3605b373603ce9b2648b9e6a1e9d0befaa4197547e438d408a790d269a0ca620bf8db9f4eeb01ecae5baf4d7983de92b2535d506e06ffcf51da18d8d397ce05c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
